### ISSUE TITLE
因为typings是动态生成的，如果要打包一份写好的复杂model，并且build出相应的d.ts文件，typescript编译会卡住

### ISSUE THREAD

**Issue by atvoid** [SpringNyan/redux-advanced#65]
请教巨佬. 因为typings是动态生成的，如果要打包一份写好的复杂的嵌套model，并且build出相应的d.ts文件，这时候typescript编译会卡住，无法生成出相应的typing文件，有没有办法解决这种情况呢？

对于一个简单的model，已经会生成出如此typing....下面只是十分之一长度
![image](https://user-images.githubusercontent.com/971824/80557895-f8669580-8a0a-11ea-9b46-8c1e19eee5a3.png)

**Comment by SpringNyan** [comment]
1. 首先确定编译时关掉incremental选项，加上这个一定会卡死 microsoft/TypeScript#31258
2. typings生成巨大是有预期的，这个library主要解决的是type的编译检查和提示，因此肯定会用到许多intersection type和mapped type
3. [SpringNyan/nyax](https://github.com/SpringNyan/nyax) 通过定义class的model从而试图解决上面两个问题

**Comment by atvoid** [comment]
incremental 是关了的
新的框架不知道能不能解决，可以试一下，巨佬有空能给个example嘛

**Comment by SpringNyan** [comment]
See [test.ts](https://github.com/SpringNyan/nyax/blob/master/test/test.ts)
